# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a65d3481dd6ccdc032fa67af8719475f6e2a61f415a0251ef8fdfb0275975a2d8965361f8ff34977ee7086bed2e8adc31fcd578740303651d6c1873c376f6d

test:
  secret_key_base: af4690e669bd6cc1aecdc839cd8d9ce34e00d48bce2aeffb9789dbbb1df35478b4879bce2da2fde8aa44312f9799352bf76814c867314ba201f5e17b78510f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
